BASE_PATH = '/users'
SEARCH_ALL_OBJECTS = 'Get User List'
SEARCH_SPECIFIC_OBJECT = 'Get User'
ADD_NEW_OBJECT = 'Add New User'
ADD_NEW_OBJECT_LIST = 'Add New User List'
REMOVE_OBJECT = 'Delete User'
UPDATE_OBJECT = 'Update User'
PATCH_OBJECT = 'Update User Partially'